version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      # args:
      #   uid: ${UID}
    container_name: laravel-app-dev-2
    # environment:
    #   - APACHE_RUN_USER=#${UID}
    #   - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8007:80
    network_mode: "host"
    restart: on-failure
    # networks:
    #   backend:
    #     aliases:
    #       - laravel-app

#   mysql-db:
#     image: mysql:5.7
#     container_name: mysql-db
#     volumes:
#       - ./run/var:/var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD=securerootpassword
#       - MYSQL_DATABASE=db
#       - MYSQL_USER=dbuser
#       - MYSQL_PASSWORD=secret
#     networks:
#       backend:
#         aliases:
#           - db

# networks:
#   backend:
#     name: backend-network